/**
 * Plan file generation and formatting
 * Creates properly formatted markdown plan files
 */

import type { PlanContent } from "./types";

/**
 * Generate the markdown content for a plan file
 */
export function generatePlanMarkdown(content: PlanContent): string {
	const lines: string[] = [];

	// Header
	lines.push(`# Plan: ${content.title}`);
	lines.push("");
	lines.push(`**ID:** ${content.id}`);
	lines.push(`**Created:** ${new Date().toISOString()}`);
	lines.push(`**Status:** pending`);
	lines.push(`**Request:** ${content.request}`);
	lines.push("");

	// Summary
	lines.push("## 📋 Summary");
	lines.push("");
	lines.push(content.summary);
	lines.push("");

	// Goals
	if (content.goals && content.goals.length > 0) {
		lines.push("## 🎯 Goals");
		lines.push("");
		for (const goal of content.goals) {
			lines.push(`- ${goal}`);
		}
		lines.push("");
	}

	// Files to change
	if (content.filesToChange && content.filesToChange.length > 0) {
		lines.push("## 📁 Files to Change");
		lines.push("");
		for (const file of content.filesToChange) {
			lines.push(`- \`${file.path}\` - ${file.description}`);
		}
		lines.push("");
	}

	// Implementation steps
	if (content.steps && content.steps.length > 0) {
		lines.push("## 🔄 Implementation Steps");
		lines.push("");
		for (let i = 0; i < content.steps.length; i++) {
			const step = content.steps[i];
			lines.push(`${i + 1}. **${step.title}**`);
			if (step.details && step.details.length > 0) {
				for (const detail of step.details) {
					lines.push(`   - ${detail}`);
				}
			}
			lines.push("");
		}
	}

	// Risks
	if (content.risks && content.risks.length > 0) {
		lines.push("## ⚠️ Risks & Mitigation");
		lines.push("");
		for (const risk of content.risks) {
			lines.push(`- **${risk.risk}**`);
			lines.push(`  - *Mitigation:* ${risk.mitigation}`);
			lines.push("");
		}
	}

	// Acceptance criteria
	if (content.acceptanceCriteria && content.acceptanceCriteria.length > 0) {
		lines.push("## ✅ Acceptance Criteria");
		lines.push("");
		for (const criterion of content.acceptanceCriteria) {
			lines.push(`- [ ] ${criterion}`);
		}
		lines.push("");
	}

	// Notes
	if (content.notes && content.notes.length > 0) {
		lines.push("## 📝 Notes");
		lines.push("");
		for (const note of content.notes) {
			lines.push(`- ${note}`);
		}
		lines.push("");
	}

	// Footer
	lines.push("---");
	lines.push("");
	lines.push("**Generated by a plan agent**");

	return lines.join("\n");
}

/**
 * Extract title from request (first 50 chars)
 */
export function extractTitleFromRequest(request: string): string {
	return request
		.split("\n")[0]
		.substring(0, 50)
		.trim()
		.replace(/[^a-zA-Z0-9\s]/g, "");
}

/**
 * Get a summary of plan content
 */
export function getSummary(content: string, maxLength: number = 200): string {
	// Extract text after first "## Summary" or "Summary" section
	const match = content.match(/## Summary\n+([^#]+)/i);
	if (match?.[1]) {
		return match[1].trim().split("\n")[0].substring(0, maxLength);
	}

	// Fallback: get first paragraph
	const firstPara = content
		.split("\n\n")[1] // Skip title
		?.trim()
		.substring(0, maxLength);

	return firstPara || "";
}
